### PR TITLE
Update Readme and requirements

### PR DESCRIPTION
**Pull request by lucyleeow**
Update readme and requirements.txt. Add environment.yml

Also updates link to ramp studio in notebook.

### CODE REVIEW

**Comment by lucyleeow** [comment]
ping @agramfort

**Comment by lucyleeow** [comment]
@agramfort both  https://ramp.studio/problems/boston_housing and  http://ramp.studio/problems/boston_housing work for me but changed the link to the https one

**Comment by agramfort** [comment]
fix in notebook missing?

**Comment by lucyleeow** [comment]
Forgot to push - should appear now. What do you want the new boston event to be named?

**Comment by agramfort** [comment]
thx @lucyleeow

**Pull request merged**
