### PR TITLE
backend

### PR DESCRIPTION
**Pull request by kegl**

### CODE REVIEW

**Comment by agramfort** [comment]
use openssl as explained here:

https://superuser.com/questions/162624/how-to-password-protect-gzip-files-on-the-command-line

see:

https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables

for protecting the password.

unzip is apparently not safe enough

@kegl give it a try

**Comment by glemaitre** [comment]
I check the following possibility:

- I set up a private/public key using Travis CLI.
- The key is encrypted in the github repo and decrypted during the pushing.
- The server with the server data as the public key.
- We will be able to fetch the data through [sftp for instance](https://github.com/glemaitre/template-ramp-kit/blob/master/.travis.yml#L38)

The full travis config is there:
https://github.com/glemaitre/template-ramp-kit/blob/master/.travis.yml

**Comment by kegl** [comment]
I'm now thinking about another scheme where backend will mirror completely the starting kit, only the data will be replaced by private data. So private data can come through another channel. I'll pull the kit on the backend, then take the data from somewhere else. Check using test_submission if the private data complies, then run a script to set up the ramp. This would mean that we can get rid of the separate backend.py and test_backend, and the zipping issue is also moot.

**Comment by agramfort** [comment]
whatever works. You just need to make sure that green travis on kit repo
means good to go on the backend

**Pull request merged**
